#!c:/Perl/bin/perl
use English;


my $filename = 'dis';
my @indices  = qw{sequences};

system qq{pdflatex $filename};
for (@indices) {
    system qq{makeindex -s sequences.ist -c $_};
}
system qq{bibtex $filename};

system qq{pdflatex $filename} for 1..3;


if ($OSNAME =~ m#^MSWin#i ) {
    system qq{copy $filename.pdf D:\\$filename.pdf};
    system qq{"F:\\Program Files\\Adobe\\Acrobat 7.0\\Reader\\AcroRd32.exe" "D:\\$filename.pdf"};
} else { # assume linux...
    system qq{acroread $filename.pdf}; 
    
}
