#!c:/Perl/bin/perl
my $filename = $ARGV[0];
my $latex_run_count;

sub RunLatex{
    my ($times) = @_;
    for ($latex_run_count+1 .. $times) {
        system("pdflatex $filename");
    }
    $latex_run_count = $times;
}

RunLatex(1);

my $more_latex_runs;
if (-e $filename . ".idx") {
    system "makeindex $filename";
    $more_latex_runs++;
}

if (-e $filename . ".aux") {
    system "bibtex $filename";
    $more_latex_runs++;
}

if ($more_latex_runs) {
    RunLatex(3);
}

if ($OSNAME =~ m#^MSWin#i ) {
    system qq{copy $filename.pdf D:\\$filename.pdf};
    system qq{"F:\\Program Files\\Adobe\\Acrobat 7.0\\Reader\\AcroRd32.exe" "D:\\$filename.pdf"};
} else { # assume linux...
    system qq{acroread $filename.pdf}; 
    
}
