#!c:/Perl/bin/perl
my $what = $ARGV[0] or die "Need argument";
my $cmd = "grep '$what' Seqsee.pl lib/*.pm lib/*/*.pm t/*.t t/*/*.t t/*/*/*.t t/*/*/*.pm t/*/*/*/*.pm t/*/*/*/*.pm Perf/*.pm Perf/*/*.pm";
system $cmd;
